In [1]:
sc = SparkContext.getOrCreate()

In [2]:
# Importação das bibliotecas que poderão ser utilizadas no algoritmo 

from PIL import Image
import timeit
import numpy as np
import cv2
time_start = timeit.default_timer()

In [3]:
# leitura da Imagem em diretório local
# criação da matriz com a identificação das matrizes b,g,r (função split)
# definiçao do Kernel 

img_foto = Image.open("/Mestrado/trabalho/losangeles.jpg")
matrizBGR   = cv2.split(np.array(img_foto))

kernel = np.array([[0,1,0],[1,1,1],[0,1,0]])
if  sum(np.reshape(kernel,-1)) == 0:
    somaKernel = 1
else:  
    somaKernel= sum(np.reshape(kernel,-1))

In [4]:
# Módulo para apresentar conteúdos Gerados

print ('estrutura da foto) = ',np.array(img_foto).shape)
print ('dimensão b = ',matrizBGR[0].shape) 
print ('dimensão g = ',matrizBGR[1].shape)  
print ('dimensão r = ',matrizBGR[2].shape)  
print ('kernel')
print (kernel)
print ('soma Kernel = ',somaKernel)


estrutura da foto) =  (1080, 2401, 3)
dimensão b =  (1080, 2401)
dimensão g =  (1080, 2401)
dimensão r =  (1080, 2401)
kernel
[[0 1 0]
 [1 1 1]
 [0 1 0]]
soma Kernel =  5


In [5]:
# algoritmo em ninhos de repetição onde processando as 3 matrizes b,g,r no ninho maior (vaviável a)
# na sequencia, geração de todas as submatrizes e através da função reshape faz a somatória dd todos os elementos da 
# submatriz 

# ao final de cada looping completo para "a", teremos a matrizComvolu com o Kernel Aplicado na sequencia b,g,r

qtdeOperac = 0
for a in range (np.array(img_foto).shape [2]):
    matrizConvolu = np.copy(matrizBGR[a])
    for x in range (matrizBGR[a].shape [0]-2):
            for y in range (matrizBGR[a].shape [1]-2):
                        subMatriz = matrizBGR[a][slice(x,x+3),slice (y,y+3)] 
                        matrizConvolu [x+1][y+1] = int(sum(np.reshape(subMatriz*kernel,-1)) / somaKernel)
                        if  matrizConvolu [x+1][y+1] < 0:
                                print (matrizConvolu [x+1][y+1])
                                matrizConvolu [x+1][y+1] = 0
                        qtdeOperac = qtdeOperac + 1
    matrizBGR[a] = matrizConvolu

In [6]:
# Quantidade de operações realizadas 

print ("Qtde Operações = ", qtdeOperac)

Qtde Operações =  7758366


In [7]:
# faz o merge das 3 matrizes b,g,r para criação da nova imagem, com o Filtro de Convolução aplicado.
# será armazenado no mesmo diretório local onde localiza-se a imagem de origem

imgArrayConvolu = cv2.merge((matrizBGR[0],matrizBGR[1],matrizBGR[2]))
Image.fromarray(imgArrayConvolu).save("/Mestrado/trabalho/Imagem_Convolu.jpg")

In [8]:
# conferencia das dimensões da imagem criada

print (imgArrayConvolu.shape)

(1080, 2401, 3)


In [9]:
# totalizados do tempo em segundos da execução completa do algoritmo

time_end = timeit.default_timer()
time = time_end - time_start
print ('Tempo de processamento Comum:', time, 'segundos')

Tempo de processamento Comum: 65.51608762818074 segundos
